---
title:
- type: main
  text: The Philosophy of Heaven and Earth
- type: subtitle
  text: Describing the indescribable
creator:
- role: author
  text: Peter Christensen
- rights: © 2016-2019 Peter Christensen, CC BY-NC-SA
...
