---
title:
- type: main
  text: Daoistic
- type: subtitle
  text: The Philosophy of Heaven and Earth
creator:
- role: author
  text: Peter Christensen
- rights: © 2016-2020 Peter Christensen, CC BY-NC-SA
...
